### ISSUE TITLE
reagent-query shows up as CSS when performing a github search

### ISSUE THREAD

**Issue by gadfly361** [brosenan/reagent-query#1]
![reagent-query](https://user-images.githubusercontent.com/8610039/31851491-b449b460-b61b-11e7-97dd-69d3746a43b8.png)

This can be solved by placing the css files in a `vendor` directory.

**Comment by brosenan** [comment]
Created 4418293782e885a7ba5b9336811da916f2b671f4 and e125453d18c2552c2ebd631732bd9158a071214e that I hope will fix this.
Stats are still as they were before (41.1% CSS), but I guess GitHub does language in some batch processing cycle so I guess we should give it a few hours / days.

I'm closing the issue for now. Please re-open if the stats remain as they are a few days from today.

**Comment by gadfly361** [comment]
@brosenan Awesome, yeah that looks like it should work :)
